# Change these first
owner: Asimovers
repo: cl-asimov-uc-status

sites:
  - name: Google
    url: https://www.google.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: Portal UC
    url: https://uc.cl
  - name: Sitio Kit Digital 
    url: https://kitdigital.uc.cl
  - name: Api Agenda UC
    url: https://api.agenda.uc.asimov.cl/
  - name: Sitio Agenda UC
    url: https://cl-uc-agenda-front.netlify.app/
    
assignees: # Users to assign downtime issues (optional)
  - eliasleyton

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.uc.asimov.cl
  # baseUrl: /
  logoUrl: https://asimov.cl/logo.svg
  name: Status UC por Asimov
  introTitle: "**Status UC** es un servicio de monitoreo de los sistemas que adminsitra para la Universidad Católica de Chile"
  introMessage: Si tiene dudas sobre este sitio por favor ponerse en contacto a direcciondigital@uc.cl o uc@asimov.cl
  css: ":root {--body-background-color: #171819;--body-text-color: #FFFFFF;--card-background-color: #232628;--nav-background-color: #232628;--nav-border-bottom-color: #232628;--nav-current-border-bottom-color: #E71324;--card-border-color: #232628;--down-border-left-color: #E73913;--down-background-color: #501407;--degraded-border-left-color: #FFC700;--up-border-left-color: #76D73A;--tag-color: #232628;--tag-up-background-color: #76D73A;--tag-down-background-color: #EF5B3B;--tag-degraded-background-color: #FFC700;--change-background-color: #f7b731;--error-button-border-color: #1a46ad;--error-button-background-color: #3867d6;--error-button-color: #ffffff;--submit-button-border-color: #1a46ad;--submit-button-background-color: #3867d6;--submit-button-color: #ffffff;--graph-opacity: 1;--graph-filter: none;}"
  navbar:
    - title: Status
      href: /
    - title: Repo
      href: https://github.com/$OWNER/$REPO
    - title: Asimov
      href: https://asimov.cl/
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  activeIncidents: Incidencias activas
  allSystemsOperational: Todos los sistemas estan operativos
  incidentReport: "Incidencia #$NUMBER reporte →"
  activeIncidentSummary: Abierta el $DATE con $POSTS actualizaciones
  incidentTitle: Incident $NUMBER Details
  incidentDetails: Incident Details
  incidentFixed: Corregido
  incidentOngoing: En curso
  incidentOpenedAt: Abierta el
  incidentClosedAt: Cerrada el
  incidentViewOnGitHub: View and Subscribe on GitHub
  incidentCommentSummary: Posted at $DATE by $AUTHOR
  incidentBack: ← Volver a todas las incidencias
  pastIncidents: Incidencias anteriores
  pastIncidentsResolved: Resuelta en $MINUTES minutos con $POSTS actualizaciones
  liveStatus: Estado actual
  overallUptime: "Tiempo de actividad: $UPTIME"
  overallUptimeTitle: Tiempo de actividad
  averageResponseTime: "Tiempo de respuesta prmedio: $TIMEms"
  averageResponseTimeTitle: Respuesta promdio
  sevelDayResponseTime: Tiempo de respuesta 7-dias
  responseTimeMs: Tiempo de respuesta (ms)
  up: Activo
  down: Down
  degraded: Degraded
  ms: ms
  loading: Loading
  navGitHub: GitHub
  footer: Esta pagina es desarrollada y mantenida por [Asimov](https://asimov.cl)
  rateLimitExceededTitle: Excede el límite
  rateLimitExceededIntro: Ha superado el número de solicitudes que puede realizar en una hora, por lo que tendrá que esperar antes de volver a acceder a este sitio web. Alternativamente, puede agregar un token de acceso personal de GitHub para continuar usando este sitio web.
  rateLimitExceededWhatDoesErrorMean: ¿A qué se refiere este error?
  rateLimitExceededErrorMeaning: Este sitio web utiliza la API de GitHub para acceder a datos en tiempo real sobre el estado de nuestros sitios web. De manera predeterminada, GitHub permite que cada dirección IP realice 60 solicitudes por hora, las que ha consumido.
  rateLimitExceededErrorHowCanFix: ¿Cómo puedo arreglarlo?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: An error occurred
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: You can try again in a few moments.
  errorHome: Go to the homepage
  pastScheduledMaintenance: Past Scheduled Maintenance
  scheduledMaintenance: Scheduled Maintenance
  scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes
  scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes
  startedAt: Started at
  startsAt: Starts at
  duration: Duration
  durationMin: $DURATION minutes
  incidentCompleted: Completed
  incidentScheduled: Scheduled
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1y
  durationAll: all